from functions.newspresso_team.newspresso_supervisor_agent import newspresso_supervisor_agent

from functions.newspresso_team.top_headlines_team.top_headlines_supervisor_agent import top_headlines_supervisor_agent
from functions.newspresso_team.top_headlines_team.top_headlines_agent import top_headlines_node
from functions.newspresso_team.top_headlines_team.top_headlines_image_agent import top_headlines_image_node

from functions.newspresso_team.podcast_team.podcast_supervisor_agent import podcast_supervisor_agent
from functions.newspresso_team.podcast_team.podcast_transcript_supervisor_agent.podcast_transcript_supervisor_agent import podcast_transcript_supervisor_agent
from functions.newspresso_team.podcast_team.podcast_audio_generator_agent import podcast_audio_generator_node

from functions.newspresso_team.podcast_team.podcast_transcript_supervisor_agent.podcast_transcript_generator_agent import podcast_transcript_generator_node
from functions.newspresso_team.podcast_team.podcast_transcript_supervisor_agent.podcast_transcript_critic_agent import podcast_transcript_critic_node

from common_imports import *
from classes import AgentState

workflow = StateGraph(AgentState)

workflow.add_node(NEWSPRESSO_SUPERVISOR_AGENT, newspresso_supervisor_agent)

workflow.add_node(TOP_HEADLINES_SUPERVISOR_AGENT, top_headlines_supervisor_agent)
workflow.add_node(TOP_HEADLINES_AGENT, top_headlines_node)
workflow.add_node(TOP_HEADLINES_IMAGE_AGENT, top_headlines_image_node)

workflow.add_node(PODCAST_SUPERVISOR_AGENT, podcast_supervisor_agent)
workflow.add_node(PODCAST_TRANSCRIPT_SUPERVISOR_AGENT, podcast_transcript_supervisor_agent)
workflow.add_node(PODCAST_AUDIO_GENERATOR_AGENT, podcast_audio_generator_node)

workflow.add_node(PODCAST_TRANSCRIPT_GENERATOR_AGENT, podcast_transcript_generator_node)
workflow.add_node(PODCAST_TRANSCRIPT_CRITIC_AGENT, podcast_transcript_critic_node)

workflow.add_edge(START, NEWSPRESSO_SUPERVISOR_AGENT)

graph = workflow.compile()

